### PR TITLE
Updated RSA spec, modified userClients and changes to testing.

### PR DESCRIPTION
**Pull request by gradyclark03**
- RSA encryption and decryption now use OAEP with SHA-256 digest function.
- RSA signing and verification now use PSS with SHA-256 digest function.
- Modified client message handler to use decryptSignedMessage function to handle signed chats. Keeping old implementation commented out for now.
- Added 3rd userClient for testing purposes.
- Added RSA decrypt error handler to determine if RSA decryption has failed.

### CODE REVIEW

**Comment by gradyclark03** [comment]
Seems to fail signature verification, but works perfectly fine on my end.

**Comment by Aegizz** [comment]
Signature signing appers to be broken, must be to do with the PSS and other changes you made.

lloyd@lloydserver:~/Desktop/Uni2024/SP2024/Tut-7-ON-Imp$ ./test-client-signature
Loaded Key
Generated signature: WGBSc/WL1m0s63pWKJ/iALEBPHDPBujx8eki+ZIkrZ5U19rf/8KlcFDZIo3aPWPPbP2Nwmfo25kSmBgBlZjGZ1i0L3RsAeaqTtE76jwsLM21PoF+pXagjFXlZ7yTqGHWnvDWZElMYwJsxnRHhStzy24tTgLE74NGG1KNZj7S0urw27jka1/MuVFsAGrSYTzwOKsKU9wUebBKZmqSa0t7PBwnnYq9hOlZ1mzlIZ8CEfwTZ0ssSjv2SesQmDEkcA3ojFnyKY9CO5tb64VIm5sSm+wn47hFIQZ6BA4VYMiMRIJx3qDiuvHlsdxfy+kttQfehQOdCu2j7dnh5GMhGbBf9g==
Signature verification failed!

**Comment by gradyclark03** [comment]
Figured out outdated OpenSSL functions are being used. Will update shortly

**Comment by gradyclark03** [comment]
Fixed now

**Pull request merged**
